### ISSUE TITLE
Receiving EADDRNOTAVAIL upon `vagrant up`

### ISSUE THREAD

**Issue by thirdgen88** [kcollins-ene/evaluator#2]
![unknown](https://cloud.githubusercontent.com/assets/7111175/24326617/4ad1f302-1180-11e7-87d0-79d359181975.png)

**Comment by kcollins-ene** [comment]
Seems like this issue:
https://github.com/mitchellh/vagrant/issues/8395

I've updated the repo with the fix from the issue above.
